version: "3.8"

services:
  api:
    container_name: api
    build:
      context: dinopass/
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8888:8000"
    volumes:
      - ./dinopass/backend:/code/backend
      - ./dinopass/backend/db:/code/db

  cli:
    container_name: cli
    build:
      context: dinopass/
      dockerfile: ./docker/cli/Dockerfile
    volumes:
      - ./dinopass/backend:/code/backend
      - ./dinopass/backend/db/dinopass.db:/code/db/dinopass.db

  frontend:
    container_name: frontend
    build:
      context: dinopass/
      dockerfile: ./docker/frontend/Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./dinopass/frontend:/code/frontend
    depends_on:
      - api