version: "3.8"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/scripts/db/:/docker-entrypoint-initdb.d/
    env_file:
      - ./backend/.db.env
    ports:
      - "5432:5432"
    restart: always
    networks:
      - dinopass

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/home/dinopass/backend/
    restart: always
    depends_on:
      - db
    networks:
      - dinopass

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/dinopass/frontend/
    depends_on:
      - backend
    networks:
      - dinopass

volumes:
    postgres_data:

networks:
  dinopass:
    name: dinopass
