[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Alexandru Grajdeanu <ext.agrajdeanua@warbyparker.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.81.0"
bcrypt = "^4.0.0"
cryptography = "^37.0.4"
asyncpg = "^0.26.0"
SQLAlchemy = "^1.4.40"
passlib = "^1.7.4"
uvicorn = "^0.18.3"
python-dotenv = "^0.20.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
